### ISSUE TITLE
Transition to native materialized views

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/pycds#26]
PostgreSQL >= 9.3 [directly supports](https://www.postgresql.org/docs/10/sql-creatematerializedview.html) materialized views. The present code supports materialized views as ordinary tables that are maintained by a set of views, functions, and triggers, evidently following [this article](http://tech.jonathangardner.net/wiki/PostgreSQL/Materialized_Views).

These manually maintained materialized views should be replaced by equivalent native materialized views. See database `dbnorth.pcic.uvic.ca/metnorth` and `https://github.com/pacificclimate/crmp/pull/1` for pure SQL definitions of equivalent native matviews.

Specifically, add the following matviews:

- [x] `vars_per_history_mv` (#73)
- [x] `station_obs_stats_mv` (#177)
- [x] `collapsed_vars_mv` (#179)
- [x] `obs_count_per_month_history_mv` (#182)
- [x] `climo_obs_count_mv` (use function `variable_tags` in definition) (#171)

**Comment by rod-glover** [comment]
The transition to native matviews will create a version of PyCDS that is not backwards compatible with the current version. It therefore must have a new major version number (3).

**Comment by rod-glover** [comment]
The CRMP instance of this database does contain substantial content not defined in PyCDS, content noted above that maintains the manual views. We are not proposing to add any support for this to PyCDS, as this transition will replace it all with native matviews.

**Comment by rod-glover** [comment]
SQLAlchemy still does not have direct support for materialized views (or regular views), apart from some [support for introspecting views](https://docs.sqlalchemy.org/en/13/changelog/changelog_11.html#change-28b7f4677e511cd22a9dd16745eed45d) and [autocommit for “REFRESH MATERIALIZED VIEW” PostgreSQL statements](https://docs.sqlalchemy.org/en/13/changelog/changelog_11.html#change-1c328da5c9c8add20c531fbb196b8543). 

Materialized views must still be supported by a compiler extension, as is done for the current fake/manual materialized views defined in `pycds/weather_anomaly.py`. A bit of research suggests that the approach currently adopted here is still good practice, and it has the further advantage of being ready to convert to native materialized views:

> The current version of these helpers has been modified simply to create and update regular tables instead of true materialized views. This enables these helpers to be used in with Postgresql versions < 9.3 (when materialized views were introduced). To restore the true materialized view functionality, revert the merge commit for the branch "fake-materialized-views".

(`pycds/materialized_view_helpers.py`)

**Comment by rod-glover** [comment]
This transition *will*, however, change the database schema. Therefore it would be best to [introduce Alembic for managing database migrations](https://github.com/pacificclimate/pycds/issues/21) before implementing native materialized views. 

That said, it's still not entirely clear how or if we will define a migration for converting manual matviews to native ones. Specifically:

- How do we plan to transition the CRMP database to a later version of PostgreSQL?
- `dbnorth/metnorth` has already had native matviews added outside of PyCDS. There will be no schema migration there.
- `dbmsc`????

@jameshiebert , can you comment here?

**Comment by rod-glover** [comment]
In adding support for native matviews, also add (or make it easy to add) support for views, which SQLAlchemy also does not support out of the box. The same technique applies. This will be used by #27 .

**Comment by rod-glover** [comment]
See also https://github.com/sqlalchemy/sqlalchemy/wiki/Views !!

**Comment by rod-glover** [comment]
1. I see your point, but would respond by saying that migrations often change a database schema to one that is incompatible with the previous one (meaning amongst other things that the new schema, expressed as an ORM, cannot be mapped onto the old). There's no contradiction here. The incompatibility is just that we'd need to use PyCDS 2 to access a database created with that schema, and PyCDS 3 to access a migrated or new database in the new schema.
1. This may be most pragmatic approach, but I think it would be worth exploring if a migration (which can include data migrations as well as schema migration) might not be the easiest way to handle this. In any case, there is no harm in introducing Alembic in nominal ver. 2, and then moving to ver. 3 with its shiny newness.

**Comment by rod-glover** [comment]
Note: The existing legacy materialized views are no doubt quite clever, but they out-clevered themselves in [at least one case](https://github.com/pacificclimate/station-data-portal/issues/160#issuecomment-1593655647). 

The simplest way to do this is to define each native matview using the corresponding legacy view that participates in the legacy manual matview update.

**Comment by rod-glover** [comment]
All matviews have been converted. Discussion re. versions is long since settled.
